# Generated by Django 4.2.3 on 2023-07-29 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('last_edit', models.DateField(auto_now=True)),
                ('comment_ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_creation_date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('tags', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('last_edit', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='article_files/')),
                ('article_ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
