# Generated by Django 4.2.3 on 2023-08-01 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comments_related_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='related_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
    ]
